### ISSUE TITLE
Bug: error @ databaseFactory.Import() when DB is on Azure

### ISSUE THREAD

**Issue by hidegh** [hherzl/CatFactory#11]
When trying scaffolding from SQL hosted on azure, I got this exception. I created a new, empty DB and added a single table but the error was the same...neither did logging with debug provide more info.

Code:
```
        public static void Main(string[] args)
        {
            Scaffold();
        }

        public static void Scaffold()
        {
            var serilog = new LoggerConfiguration()
                .MinimumLevel.Debug()
                .WriteTo.Console()
                .CreateLogger();

            var loggerFactory = new LoggerFactory()
                .AddSerilog(serilog);

            Microsoft.Extensions.Logging.ILogger logger = loggerFactory.CreateLogger<SqlServerDatabaseFactory>();
            
            // Create database factory
            var databaseFactory = new SqlServerDatabaseFactory(logger)
            {
                DatabaseImportSettings = new DatabaseImportSettings
                {
                    ConnectionString = "Server=tcp:Xxx.database.windows.net,1433;Initial Catalog=azure-test-db;User Id=Xxx;Password=Xxx;",
                    ImportTables = true
                }
            };
            
            // Import database
            var database = databaseFactory.Import();
```

Exception:
```
System.InvalidCastException
  HResult=0x80004002
  Message=Object cannot be cast from DBNull to other types.
  Source=System.Private.CoreLib
  StackTrace:
   at System.DBNull.System.IConvertible.ToInt32(IFormatProvider provider)
   at System.Convert.ToInt32(Object value)
   at CatFactory.SqlServer.SqlServerDatabaseFactory.SetIdentity(View view, IDictionary`2 dictionary)
   at CatFactory.SqlServer.SqlServerDatabaseFactory.<GetViewsAsync>d__41.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CatFactory.SqlServer.SqlServerDatabaseFactory.<ImportAsync>d__19.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at CatFactory.SqlServer.SqlServerDatabaseFactory.Import()
   at Xxx.DbContext.Program.Scaffold() in C:\$_Work\Xxx.DbContext\Program.cs:line 36
   at Xxx.DbContext.Program.Main(String[] args) in C:\$_Work\Xxx.DbContext\Program.cs:line 13

  This exception was originally thrown at this call stack:
    [External Code]
    Xxx.DbContext.Program.Scaffold() in Program.cs
    Xxx.DbContext.Program.Main(string[]) in Program.cs	
```

**Comment by hherzl** [comment]
This issue belongs to [CatFactory.SqlServer](https://github.com/hherzl/CatFactory.SqlServer) repository, but I'll work on this the next week

**Comment by spuddus** [comment]
I had the same issue, for some reason 1 system view is creeping into the views object collection when it is sent to the GetViewsAsync call on an Azure database.

sys.database_firewall_rules

It is a view specific to Azure, so most likely is a Microsoft issue where the permissions are not set correctly.

https://docs.microsoft.com/en-us/sql/relational-databases/system-catalog-views/sys-database-firewall-rules-azure-sql-database?view=azuresqldb-current
